### ISSUE TITLE
Flutter version 2.10.1 is not found in upstream origin

### ISSUE THREAD

**Issue by sabaridev** [EE/heroku-buildpack-flutter-light#8]
<img width="1143" alt="Screenshot 2022-03-03 at 10 15 58 PM" src="https://user-images.githubusercontent.com/98799843/156611058-6e8821bf-f039-4e8f-b1fd-dbe1a621645a.png">

**Comment by ludwiktrammer** [comment]
Should be now fixed by #9 . @sabaridev Can you please verify on you end?

**Comment by eliezerp3** [comment]
@ludwiktrammer Having this same issue
